const rows = [
    {
      id: 3232323,
      avatar: "avatar",
      userName: "First User Full Name",
      phone: "(066) 333 22 11",
      email: "Fullstack@gmail.com",
      dateActivity: "20/05/24 14:15",
      channels: [
        {
          channelComeFrom: "t.me#558899",
          activationDate: "21/01/24",
          activity: 2,
        },
        {
          channelComeFrom: "tiktok#558899",
          activationDate: "25/02/24",
          activity: 8,
        },
      ],
      location: "Kyiv region",
      salaryMin: 1000,
      salaryMax: 2000,
      currency: "$",
      comment:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      technologies: [
        "React native",
        "JavaScript",
        "Flutter",
        "Angular",
        "Python",
      ],
      actions: [
        { title: "TLG", data: "+" },
        { title: "TikTok", data: "+" },
        { title: "Activity", data: "Resently" },
        { title: "Messeges", data: "18" },
        { title: "Archive", data: "5" },
        { title: "Share", data: "" },
      ],
      status: "New",
      channelName: "http://...",
      details: "",
    },
    {
      id: 434343,
      avatar: "avatar",
      userName: "Second User Full Name",
      phone: "(067) 444 33 22",
      email: "frontend@gmail.com",
      dateActivity: "25/06/24 16:17",
      channels: [
        {
          channelComeFrom: "tiktok#669900",
          activationDate: "15/05/24",
          activity: 15,
        },
      ],
      location: "Lwiw region",
      salaryMin: 1000,
      salaryMax: 2000,
      currency: "€",
      comment: "Lorem ipsum",
      technologies: [
        "React",
        "JavaScript",
        "Flutter",
        "Angular",
        "Python",
      ],
      actions: [
        { title: "TLG", data: "-" },
        { title: "TikTok", data: "+" },
        { title: "Activity", data: "Resently" },
        { title: "Messeges", data: "10" },
        { title: "Archive", data: "2" },
        { title: "Share", data: "" },
      ],
      status: "Process",
      channelName: "http://...",
      details: "",
    },
    {
      id: 545454,
      avatar: "avatar",
      userName: "Third User Full Name",
      phone: "(099) 555 44 33",
      email: "backend@gmail.com",
      dateActivity: "11/07/24 19:27",
      channels: [
        {
          channelComeFrom: "t.me#558899",
          activationDate: "21/01/24",
          activity: 34,
        },
      ],
      location: "Odessa region",
      salaryMin: 1000,
      salaryMax: 2000,
      currency: "₴",
      comment:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      technologies: [
        "React native",
        "JavaScript",
        "NodeJS",
        "Angular",
        "Python",
      ],
      actions: [
        { title: "TLG", data: "+" },
        { title: "TikTok", data: "-" },
        { title: "Activity", data: "Resently" },
        { title: "Messeges", data: "9" },
        { title: "Archive", data: "22" },
        { title: "Share", data: "" },
      ],
      status: "Compl",
      channelName: "http://...",
      details: "",
    },
  ];
  
  export const userdata = {
    id: 3232323,
    avatar: "avatar",
    name: "User Full Name",
    phone: "(066) 333 22 11",
    email: "Fullstack@gmail.com",
    channels: [
      {
        channelComeFrom: "t.me#558899",
        activationDate: "21/01/24",
        activity: 2,
      },
      {
        channelComeFrom: "tiktok#558899",
        activationDate: "25/02/24",
        activity: 8,
      },
    ],
    location: "Lviv region",
    salaryMin: 1000,
    salaryMax: 2000,
    currency: "$",
    comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    technologies: [
      "React native",
      "JavaScript",
      "Flutter",
      "Angular",
      "Python",
    ],
    actions: [
      { title: "TLG", data: "+" },
      { title: "TikTok", data: "+" },
      { title: "Activity", data: "Resently" },
      { title: "Messeges", data: "18" },
      { title: "Archive", data: "5" },
      { title: "Share", data: "" },
    ],
  };
  
  export default rows;